version: '3'

services:
  php:
    container_name: setup-php
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    volumes:
      - ./webserver:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - setup-network-article

  nginx:
    container_name: setup-nginx
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    ports:
      - '8080:80'
      - '443:443'
    volumes:
      - ./webserver:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - setup-network-article

  mysql:
    container_name: mysql-article
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    tty: true
    volumes:
      - setup-data-article:/var/lib/mysql/
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - setup-network-article
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: article
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password

  phpmyadmin:
    container_name: setup-phpmyadmin
    image: phpmyadmin:5.2
    restart: always
    ports:
      - '8888:80'
    networks:
      - setup-network-article
    environment:
      PMA_HOST: mysql-article
    depends_on:
      - mysql

networks:
  setup-network-article:
    driver: bridge


volumes:
  setup-data-article:
    driver: local